import { Metadata } from 'next';
import Link from 'next/link';
import PageHero from '@/components/shared/PageHero';

export const metadata: Metadata = {
  title: 'Terms of Service | The Ayotunde Oso Foundation',
  description: 'Terms and conditions governing use of The Ayotunde Oso Foundation website and services.',
};

const LAST_UPDATED = 'June 30, 2025';

export default function TermsPage() {
  return (
    <main className="min-h-screen">
      <PageHero
        eyebrow="Legal"
        title="Terms of Service"
        subtitle={`Last updated: ${LAST_UPDATED}`}
        gradient="green"
        breadcrumbs={[{ label: 'Terms of Service', href: '/terms' }]}
      />

      <section className="py-16 bg-white">
        <div className="container mx-auto px-4 max-w-4xl">
          <div className="prose prose-gray max-w-none">

            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-4">1. Acceptance of Terms</h2>
            <p className="text-gray-600 leading-relaxed">By accessing and using the website of The Ayotunde Oso Foundation (&quot;AOF&quot;, &quot;we&quot;, &quot;us&quot;, &quot;our&quot;) at ayotundeosofouncation.org, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our website.</p>

            <h2 className="text-xl font-bold text-gray-900 mt-10 mb-4">2. Use of the Website</h2>
            <p className="text-gray-600 leading-relaxed">You may use this website for lawful purposes only. You agree not to:</p>
            <ul className="text-gray-600 space-y-2">
              <li>Use the site in any way that violates applicable local, national, or international laws or regulations</li>
              <li>Transmit unsolicited advertising or promotional material</li>
              <li>Attempt to gain unauthorized access to any part of the website or its infrastructure</li>
              <li>Use automated tools to scrape, crawl, or harvest content without permission</li>
              <li>Impersonate AOF, our staff, or any other person or entity</li>
              <li>Submit false or misleading information through any form on the website</li>
            </ul>

            <h2 className="text-xl font-bold text-gray-900 mt-10 mb-4">3. Donations</h2>
            <p className="text-gray-600 leading-relaxed">All donations made through this website are voluntary contributions to AOF’s mission. By making a donation, you acknowledge that:</p>
            <ul className="text-gray-600 space-y-2">
              <li>Donations are generally non-refundable, though AOF may consider refund requests made within 30 days for documented errors</li>
              <li>AOF will use donations in accordance with its stated programs and mission</li>
              <li>Tax deductibility depends on applicable laws in your jurisdiction; consult a tax professional</li>
              <li>Designated gifts will be directed to the specified program, but AOF reserves the right to redirect funds if a program changes or ends</li>
              <li>Recurring donations can be cancelled at any time through your donor portal or by contacting us</li>
            </ul>

            <h2 className="text-xl font-bold text-gray-900 mt-10 mb-4">4. User Accounts</h2>
            <p className="text-gray-600 leading-relaxed">Creating an account on our website is subject to the authentication terms of Clerk, our third-party authentication provider. You are responsible for maintaining the security of your account credentials. You must notify us immediately if you suspect unauthorized access to your account. AOF is not liable for any loss resulting from unauthorized use of your account.</p>

            <h2 className="text-xl font-bold text-gray-900 mt-10 mb-4">5. Intellectual Property</h2>
            <p className="text-gray-600 leading-relaxed">All content on this website — including text, graphics, logos, images, audio clips, and software — is the property of AOF or its content suppliers and is protected by applicable intellectual property laws. You may not reproduce, distribute, or create derivative works without our express written permission.</p>
            <p className="text-gray-600 leading-relaxed">The AOF name, logo, and all related marks are trademarks of The Ayotunde Oso Foundation. Unauthorized use is prohibited.</p>

            <h2 className="text-xl font-bold text-gray-900 mt-10 mb-4">6. KOMAI AI Assistant</h2>
            <p className="text-gray-600 leading-relaxed">Our KOMAI AI assistant is provided for informational purposes only. Responses generated by KOMAI are AI-generated and may not be accurate, complete, or up to date. KOMAI does not provide legal, medical, financial, or professional advice. Do not make important decisions based solely on KOMAI’s responses. Always verify important information with qualified professionals or official AOF communications.</p>

            <h2 className="text-xl font-bold text-gray-900 mt-10 mb-4">7. Disclaimer of Warranties</h2>
            <p className="text-gray-600 leading-relaxed">This website is provided &quot;as is&quot; without warranties of any kind, express or implied. AOF does not warrant that the website will be uninterrupted, error-free, or free of viruses. We reserve the right to modify, suspend, or discontinue any part of the website at any time without notice.</p>

            <h2 className="text-xl font-bold text-gray-900 mt-10 mb-4">8. Limitation of Liability</h2>
            <p className="text-gray-600 leading-relaxed">To the fullest extent permitted by law, AOF shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of this website or our services. Our total liability for any claim shall not exceed the amount you donated in the 12 months preceding the claim, or NGN 100,000, whichever is less.</p>

            <h2 className="text-xl font-bold text-gray-900 mt-10 mb-4">9. Third-Party Links</h2>
            <p className="text-gray-600 leading-relaxed">Our website may contain links to third-party websites. These links are provided for convenience only. AOF does not endorse or take responsibility for the content, privacy practices, or accuracy of third-party websites. Visiting third-party sites is at your own risk.</p>

            <h2 className="text-xl font-bold text-gray-900 mt-10 mb-4">10. Governing Law</h2>
            <p className="text-gray-600 leading-relaxed">These Terms of Service are governed by and construed in accordance with the laws of the Federal Republic of Nigeria. Any disputes arising from these terms or your use of this website shall be subject to the exclusive jurisdiction of the courts of Lagos State, Nigeria.</p>

            <h2 className="text-xl font-bold text-gray-900 mt-10 mb-4">11. Changes to Terms</h2>
            <p className="text-gray-600 leading-relaxed">We may revise these terms from time to time. The most current version will always be posted on this page. Continued use of the website after changes constitutes acceptance of the revised terms.</p>

            <h2 className="text-xl font-bold text-gray-900 mt-10 mb-4">12. Contact</h2>
            <p className="text-gray-600 leading-relaxed">For questions about these Terms of Service, contact us at <a href="mailto:legal@ayotundeosofouncation.org" className="text-brand-green hover:underline">legal@ayotundeosofouncation.org</a>.</p>

            <div className="mt-12 pt-8 border-t">
              <p className="text-sm text-gray-500">See also: <Link href="/privacy" className="text-brand-green hover:underline">Privacy Policy</Link> · <Link href="/cookies" className="text-brand-green hover:underline">Cookie Policy</Link> · <Link href="/accessibility" className="text-brand-green hover:underline">Accessibility Statement</Link></p>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
